# Generated by Django 4.1.3 on 2023-08-07 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0003_convocatoria_activa'),
    ]

    operations = [
        migrations.CreateModel(
            name='FechasPremios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_inicio', models.TextField()),
                ('f_fin', models.TextField()),
            ],
        ),
    ]
