# Generated by Django 4.1.3 on 2023-08-07 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0004_fechaspremios'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fechaspremios',
            name='f_fin',
        ),
        migrations.RemoveField(
            model_name='fechaspremios',
            name='f_inicio',
        ),
        migrations.AddField(
            model_name='fechaspremios',
            name='f_inicio',
            field=models.TextField()
        ),
        migrations.AddField(
            model_name='fechaspremios',
            name='f_fin',
            field=models.TextField()
        ),
    ]
