# Generated by Django 4.1.3 on 2023-08-10 15:41

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import investigadores.models
import investigadores.validators


class Migration(migrations.Migration):

    dependencies = [
        ('investigadores', '0034_investigador_constancia'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaA',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='investigadores.investigador', verbose_name='Investigador')),
                ('a1', models.FileField(blank=True, default=None, null=True, upload_to=investigadores.models.rutaCategoriaA, validators=[django.core.validators.FileExtensionValidator(['pdf'], investigadores.validators.limite10MbArchivo)], verbose_name='Artículos científicos en revistas indexadas o arbitradas.')),
                ('a2', models.FileField(blank=True, default=None, null=True, upload_to=investigadores.models.rutaCategoriaA, validators=[django.core.validators.FileExtensionValidator(['pdf'], investigadores.validators.limite10MbArchivo)], verbose_name='Autoría y coautoría de libros y/o capítulos de libros científicos con arbitraje.')),
                ('a3', models.FileField(blank=True, default=None, null=True, upload_to=investigadores.models.rutaCategoriaA, validators=[django.core.validators.FileExtensionValidator(['pdf'], investigadores.validators.limite10MbArchivo)], verbose_name='Trámite de solicitud u obtención de patentes.')),
                ('a4', models.FileField(blank=True, default=None, null=True, upload_to=investigadores.models.rutaCategoriaA, validators=[django.core.validators.FileExtensionValidator(['pdf'], investigadores.validators.limite10MbArchivo)], verbose_name='Trámite de solicitud u obtención de derechos de obtentor.')),
                ('a5', models.FileField(blank=True, default=None, null=True, upload_to=investigadores.models.rutaCategoriaA, validators=[django.core.validators.FileExtensionValidator(['pdf'], investigadores.validators.limite10MbArchivo)], verbose_name='Desarrollo de software/hardware con Derechos de Autor.')),
                ('a6', models.FileField(blank=True, default=None, null=True, upload_to=investigadores.models.rutaCategoriaA, validators=[django.core.validators.FileExtensionValidator(['pdf'], investigadores.validators.limite10MbArchivo)], verbose_name='Implementaciones tecnológicas')),
                ('a7', models.FileField(blank=True, default=None, null=True, upload_to=investigadores.models.rutaCategoriaA, validators=[django.core.validators.FileExtensionValidator(['pdf'], investigadores.validators.limite10MbArchivo)], verbose_name='Artículos o notas científicas publicadas en revistas arbitradas de divulgación científica o tecnológica.')),
                ('a8', models.FileField(blank=True, default=None, null=True, upload_to=investigadores.models.rutaCategoriaA, validators=[django.core.validators.FileExtensionValidator(['pdf'], investigadores.validators.limite10MbArchivo)], verbose_name='Participación en proyectos de investigación, desarrollo tecnológico e innovación con financiamiento externo obtenido mediante convocatoria.')),
                ('a9', models.FileField(blank=True, default=None, null=True, upload_to=investigadores.models.rutaCategoriaA, validators=[django.core.validators.FileExtensionValidator(['pdf'], investigadores.validators.limite10MbArchivo)], verbose_name='Editor, compilador o coordinador de libros colectivos.')),
                ('a10', models.FileField(blank=True, default=None, null=True, upload_to=investigadores.models.rutaCategoriaA, validators=[django.core.validators.FileExtensionValidator(['pdf'], investigadores.validators.limite10MbArchivo)], verbose_name='Pertenencia al Sistema Nacional de Investigadores.')),
                ('estatus', models.CharField(choices=[('E', 'En revisión'), ('P', 'En proceso'), ('A', 'Aceptada'), ('R', 'Rechazada'), ('F', 'Finalizada')], default='A', max_length=1, verbose_name='Estatus de la solicitud')),
            ],
        ),
    ]
