# Generated by Django 4.1.3 on 2023-08-10 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigadores', '0035_categoriaa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriaa',
            name='estatus',
            field=models.CharField(choices=[('E', 'En revisión'), ('P', 'En proceso'), ('A', 'Aceptada'), ('R', 'Rechazada'), ('F', 'Finalizada')], default='E', max_length=1, verbose_name='Estatus de la solicitud'),
        ),
    ]
