# Generated by Django 4.1.3 on 2023-08-13 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigadores', '0037_alter_categoriaa_estatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriaa',
            name='estatus',
            field=models.CharField(choices=[('I', 'En proceso'), ('E', 'En revisión'), ('G', 'Ganador'), ('F', 'Finalizada')], default='I', max_length=1, verbose_name='Estatus de la solicitud'),
        ),
    ]
