# Generated by Django 4.1.3 on 2023-08-13 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigadores', '0038_alter_categoriaa_estatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriaa',
            name='anio',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
