# Generated by Django 4.1.3 on 2023-08-14 17:37

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import investigadores.models
import investigadores.validators


class Migration(migrations.Migration):

    dependencies = [
        ('investigadores', '0039_categoriaa_anio'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaB',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='investigadores.investigador', verbose_name='Investigador')),
                ('b1', models.FileField(blank=True, default=None, null=True, upload_to=investigadores.models.rutaCategoriaB, validators=[django.core.validators.FileExtensionValidator(['pdf'], investigadores.validators.limite10MbArchivo)], verbose_name='Obtención del grado académico de Doctorado o Maestría o Especialidad de los programas del SNP o en el extranjero con beca CONACYT.')),
                ('b2', models.FileField(blank=True, default=None, null=True, upload_to=investigadores.models.rutaCategoriaB, validators=[django.core.validators.FileExtensionValidator(['pdf'], investigadores.validators.limite10MbArchivo)], verbose_name='Obtención del grado académico de Doctorado o Maestría o Especialidad de un programa nacional.')),
                ('b3', models.FileField(blank=True, default=None, null=True, upload_to=investigadores.models.rutaCategoriaB, validators=[django.core.validators.FileExtensionValidator(['pdf'], investigadores.validators.limite10MbArchivo)], verbose_name='Dirección de Tesis o Artículo de Investigación de alumnos graduados en licenciatura, maestría, doctorado o especialidad médica.')),
                ('b4', models.FileField(blank=True, default=None, null=True, upload_to=investigadores.models.rutaCategoriaB, validators=[django.core.validators.FileExtensionValidator(['pdf'], investigadores.validators.limite10MbArchivo)], verbose_name='Dirección de tesis de licenciatura de alumnos graduados en la modalidad de artículo científico.')),
                ('b5', models.FileField(blank=True, default=None, null=True, upload_to=investigadores.models.rutaCategoriaB, validators=[django.core.validators.FileExtensionValidator(['pdf'], investigadores.validators.limite10MbArchivo)], verbose_name='Presentación de ponencias o carteles en eventos científicos, en México o el extranjero.')),
                ('b6', models.FileField(blank=True, default=None, null=True, upload_to=investigadores.models.rutaCategoriaB, validators=[django.core.validators.FileExtensionValidator(['pdf'], investigadores.validators.limite10MbArchivo)], verbose_name='Estancias de investigación en instituciones académicas o de investigación.')),
                ('b7', models.FileField(blank=True, default=None, null=True, upload_to=investigadores.models.rutaCategoriaB, validators=[django.core.validators.FileExtensionValidator(['pdf'], investigadores.validators.limite10MbArchivo)], verbose_name='Asignaturas con créditos impartidas en Especialidad, Maestría o Doctorado de programas del SNP.')),
                ('b8', models.FileField(blank=True, default=None, null=True, upload_to=investigadores.models.rutaCategoriaB, validators=[django.core.validators.FileExtensionValidator(['pdf'], investigadores.validators.limite10MbArchivo)], verbose_name='Participación en proyectos de investigación con financiamiento interno o externo.')),
                ('b9', models.FileField(blank=True, default=None, null=True, upload_to=investigadores.models.rutaCategoriaB, validators=[django.core.validators.FileExtensionValidator(['pdf'], investigadores.validators.limite10MbArchivo)], verbose_name='Publicación de artículos en revistas de divulgación científica o tecnológica no arbitradas.')),
                ('b10', models.FileField(blank=True, default=None, null=True, upload_to=investigadores.models.rutaCategoriaB, validators=[django.core.validators.FileExtensionValidator(['pdf'], investigadores.validators.limite10MbArchivo)], verbose_name='Evaluación de trabajos de investigación o proyectos.')),
                ('estatus', models.CharField(choices=[('I', 'En proceso'), ('E', 'En revisión'), ('G', 'Ganador'), ('F', 'Finalizada')], default='I', max_length=1, verbose_name='Estatus de la solicitud')),
                ('anio', models.CharField(blank=True, max_length=5, null=True)),
            ],
        ),
    ]
